version: "2"
services:
 application:
    image: latest
    container_name: customer_segmentation
    ports:
      - "8080:8080"
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - MONGO_DB_URL=${MONGO_DB_URL}
        - BUCKET_NAME=${BUCKET_NAME}
        - AWS_ECR_LOGIN_URI=610577909467.dkr.ecr.ap-south-1.amazonaws.com
        - ECR_REPOSITORY_NAME=customer_segmentation
